### ISSUE TITLE
ErrorHandler calls too many times

### ISSUE THREAD

**Issue by matyunya** [getsentry/raven-php#264] opened 2016-03-01 10:11 UTC
For some errors Raven triggers same callUserFunc in handleError far too many times, besides grouping fails because of random number of such calls. Maybe set some kind of limit for handleError?

<img width="979" alt="screen shot 2016-03-01 at 13 08 45" src="https://cloud.githubusercontent.com/assets/2044570/13423902/ca404580-dfae-11e5-9c1b-a58697793dd3.png">

**Comment by gephaest** [comment] 2016-03-30 08:21
I have same problem! 
```
return call_user_func($this->old_error_handler, $code, $message, $file, $line, $context);
```
calls recursively 
See https://github.com/getsentry/raven-php/blob/master/lib/Raven/ErrorHandler.php#L191

**Comment by gephaest** [comment] 2016-03-30 09:31
Try to run
```php
<?php
require 'vendor/autoload.php';
ini_set('max_execution_time', 10);
$f = fsockopen('test_ignore_it', 12345, $erno, $errstr, 2);
```
And see on recursion hell

**Comment by dcramer** [comment] 2016-03-30 19:30
Two possibilities:

- the old handler is being registered as the current handler (actual recursion)
- the handler is being registered repeatedly thus it looks like the same in the stack but is actually different

Could the latter possibly be true for you?

**Comment by gephaest** [comment] 2016-03-31 07:01
First. In the `registerErrorHandler()` method  the `old_error_handler` attribute set to  `handleError`. When a PHP error happens `handleError` is called:
```php
    public function registerErrorHandler($call_existing_error_handler = true, $error_types = -1)
    {
        $this->error_types = $error_types;
        $this->old_error_handler = set_error_handler(array($this, 'handleError'), error_reporting());
        $this->call_existing_error_handler = $call_existing_error_handler;
    }

    // <...>

    public function handleError($code, $message, $file = '', $line = 0, $context=array())
    {
        // remove unnecessary stuff here
        if ($this->call_existing_error_handler) { // by default its true, see registerErrorHandler defenition
            if ($this->old_error_handler) { // its handleError
                return call_user_func($this->old_error_handler, $code, $message, $file, $line, $context); // we go to recursion  here
            } else {
                return false;
            }
        }
    }
```

Actually it can be fixed by setting the `$call_existing_error_handler` parameter to false, but it'a a bug and most of people just copy code listings from docs.
I don't know what this code must doing, but in my opinion `registerErrorHandler` must looks like:
```php
    public function registerErrorHandler($error_types = -1, $error_handler = null)
    {
        $this->error_types = $error_types;
        if($error_handler !== null && is_callable($error_handler)) {
            $this->old_error_handler = set_error_handler($error_handler, error_reporting());
        }
    }


    public function handleError($code, $message, $file = '', $line = 0, $context=array())
    {
        if ($this->error_types & $code & error_reporting()) {
            $e = new ErrorException($message, 0, $code, $file, $line);
            $this->handleException($e, true, $context);
        }

        if ($this->old_error_handler !== null && is_callable($this->old_error_handler)) {
            return call_user_func($this->old_error_handler, $code, $message, $file, $line, $context);
        } else {
            return false;
        }
    }
```
This makes it possible for developers pass their own work that must be done within Raven (like write to text log or something similar)

**Comment by dcramer** [comment] 2016-03-31 07:32
Maybe I'm misunderstanding but isn't set_error_handler only ever returning a previously set handler (or null if none defined)? It's not clear to me how it would get set to itself unless you were calling it multiple times.

**Comment by matyunya** [comment] 2016-03-31 11:32
> Actually it can be fixed by setting the $call_existing_error_handler parameter to false
Double that. This fixed my problem and another one where Compat inevitably ran out of memory for the very same reason. I suggest switching $call_existing_error_handler default value to false. Thank you guys!

**Comment by gephaest** [comment] 2016-03-31 11:49
> Maybe I'm misunderstanding but isn't set_error_handler only ever returning a previously set handler (or null if none defined)?

Let's see how code executed:
* Developer registers the error handler in his code:
```php
$client = new Raven_Client($sentry_dsn, $options);
$error_handler = new Raven_ErrorHandler($client);
$error_handler->registerErrorHandler(false);
```
* In the `registerErrorHandler` the `$this->old_error_handler` sets to the `handleError`:
```php
$this->old_error_handler = set_error_handler(array($this, 'handleError'), error_reporting());
```
* PHP error happens
* `handleError()` will call
```php
        if ($this->call_existing_error_handler) { // By default it's true (see the registerErrorHandler definition)
            if ($this->old_error_handler) { // This is points to handleError
                // Below handleError calls recursively
                return call_user_func($this->old_error_handler, $code, $message, $file, $line, $context);
            } else {
                return false;
            }
        }
```

P.S.: please sorry for my not so good English!

**Comment by dcramer** [comment] 2016-03-31 18:27
@gephaest this is not correct. I confirmed that the error handler *does not* get bound to itself. The result of ``set_error_handler`` is not the *new* error handler, but any previous one that is set:

```
Returns a string containing the previously defined error handler (if any). If the built-in error handler is used NULL is returned. NULL is also returned in case of an error such as an invalid callback. If the previous error handler was a class method, this function will return an indexed array with the class and the method name.
```

You can very easily change this by augmenting the source code to make $old_error_handler public:

```
<?php

require('../lib/Raven/Autoloader.php');

Raven_Autoloader::register();

$dsn = null;

$client = new Raven_Client($dsn);
$error_handler = new Raven_ErrorHandler($client);
$error_handler->registerErrorHandler(false);


var_dump($error_handler->old_error_handler);
```

The issue is almost certainly that you are registering multiple error handlers, as I can see no possible way that it would ever recurse here.

**Closed by dcramer** 2016-03-31 18:27 UTC
